---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[simple-scala-sbt::default]
    attributes:
      simple-scala-sbt:
        version: '0.13.0-0.1-build-001'
